### ISSUE TITLE
如果新增数据，都以弹框形式体验就直线上升了

### ISSUE THREAD

**Issue by powhd** [bu6030/stock-and-fund#2]
还是很好用的

**Comment by bu6030** [comment]
您能具体说下么？我不太理解，现在不就是点击添加按钮弹出页面新增么？

**Comment by bu6030** [comment]
是不是这个效果，改成bootstrap的模态框
![image](https://user-images.githubusercontent.com/11482988/189293983-1ee1989a-0284-4bb5-9bf9-150068b118bd.png)

**Comment by bu6030** [comment]
Layui的和Bootstrap的都已经改成模态框了，你可以试试怎么样

**Comment by bu6030** [comment]
已经解决，如果解决的不对，您再提issue
